# Generated by Django 6.0.6 on 2026-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_transfergroup_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
