# Generated by Django 6.0.6 on 2026-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_alter_transaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="can_be_negative",
            field=models.BooleanField(default=False),
        ),
    ]
